### ISSUE TITLE
error 1.20.1

### ISSUE THREAD

**Issue by phys1cs27** [plasmoapp/pv-addon-discs#17]
[19:37:30 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/pv-addon-discs-1.0.5.jar' in 'plugins'

org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [pv-addon-lavaplayer-lib]. Please download and install these plugins to run 'pv-addon-discs'.

at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[purpur-1.20.1.jar:git-Purpur-2014]

at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2014]

at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2014]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.1.jar:git-Purpur-2014]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2014]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2014]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by phys1cs27** [comment]
Я дурак, либу не поставил, проблема решена
