### ISSUE TITLE
[error] Playback error | Ошибка воспроизведения

### ISSUE THREAD

**Issue by Phanvoy1** [plasmoapp/pv-addon-discs#27]
[19:54:25] [lava-daemon-pool-playback-1-thread-1/ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of EScWQN25LCw
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:346) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 4.15.0-213-generic
  java.vendor: Private Build
  java.version: 17.0.7
  java.runtime.version: 17.0.7+7-Ubuntu-0ubuntu118.04
  java.vm.version: 17.0.7+7-Ubuntu-0ubuntu118.04
Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:308) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069) ~[?:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:120) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream.internalRead(YoutubePersistentHttpStream.java:52) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream.internalRead(YoutubePersistentHttpStream.java:76) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:193) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MutableMatroskaBlock.getNextFrameBuffer(MutableMatroskaBlock.java:54) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[pv-addon-lavaplayer-lib-1.0.5.jar:?]
	... 10 more

**Comment by Apehum** [comment]
Sorry for the late response. By the error `Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out` I can tell, that your host can't reach the youtube/(or whatever you using). It's the issue with connection, so I can't do anything about it.
