### ISSUE TITLE
v 1.0.5 Is it up to date? error

### ISSUE THREAD

**Issue by ICPO** [plasmoapp/pv-addon-discs#30]
[PlasmoVoice] Loading PlasmoVoice v2.0.7
[17:06:34] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.1.0
[17:06:35] [Server thread/INFO]: [pv-addon-lavaplayer-lib] Loading pv-addon-lavaplayer-lib v1.0.5
[17:06:35] [Server thread/INFO]: [pv-addon-discs] Loading pv-addon-discs v1.0.5
[17:06:35] [Server thread/INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.7
[17:06:35] [Server thread/INFO]: pv-addon-lavaplayer-lib v1.0.5 by Apehum loaded
[17:06:35] [Server thread/INFO]: pv-addon-discs v1.0.5 by KPidS loaded
[17:06:35] [Server thread/INFO]: UDP server is started on /[0:0:0:0:0:0:0:0]:25565
[17:06:35] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[17:06:35] [Server thread/INFO]: [pv-addon-lavaplayer-lib] Enabling pv-addon-lavaplayer-lib v1.0.5
[17:06:35] [Server thread/INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.0.5
[17:06:35] [Server thread/ERROR]: Error occurred while enabling pv-addon-discs v1.0.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.io.File org.bukkit.Bukkit.getPluginsFolder()'
        at su.plo.voice.discs.AddonConfig$Companion.getAddonFolder(AddonConfig.kt:168) ~[?:?]
        at su.plo.voice.discs.AddonConfig$Companion.loadConfig(AddonConfig.kt:142) ~[?:?]
        at su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:106) ~[?:?]
        at su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
        
how fix it ? 1.0.5 - latest version for 1.20.1.. or not ?

**Comment by s3nkwr** [comment]
Use [PaperMC](https://papermc.io/downloads/paper)
