### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dezyka** [plasmoapp/pv-addon-discs#31]
- [Mon 13:11:36 ERROR su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of _v-ah9tyXHs
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:346)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
    Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 5.10.0-23-amd64
  java.vendor: Debian
  java.version: 17.0.7
  java.runtime.version: 17.0.7+7-Debian-1deb11u1
  java.vm.version: 17.0.7+7-Debian-1deb11u1
Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:56)
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
    at pv-addon-lavaplayer-lib-1.0.6.jar//su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudio

**Comment by MagmaBro123** [comment]
Dead project. Don't bother using.

**Comment by Dezyka** [comment]
> Dead project. Don't bother using.

Could you recommend something to replace this plugin?  I heard about Simple Voice Chat and its addons, but I don’t like that there is no direct download of audio from YouTube, you can only download it from file hosting services, or direct download to server files.

**Comment by MagmaBro123** [comment]
I'm not aware of anything besides this or SVC.

**Comment by Apehum** [comment]
Sorry for the late response. By the error `Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out` I can tell, that your host can't reach the youtube/(or whatever you using). It's the issue with connection, so I can't do anything about it.
