### ISSUE TITLE
Не работает плагин

### ISSUE THREAD

**Issue by inferna337** [plasmoapp/pv-addon-discs#36]
плагин установлен нужной версии и все вспомогательные моды установлены

строка с ошибкой:

<html>
<body>

[Server thread/ERROR] [Minecraft/]: Error occurred while enabling pv-addon-discs v1.0.5 (Is it up to date?)
--
69 | java.lang.NoSuchMethodError: 'java.io.File org.bukkit.Bukkit.getPluginsFolder()'
70 | at su.plo.voice.discs.AddonConfig$Companion.getAddonFolder(AddonConfig.kt:168) ~[?:?] {}
71 | at su.plo.voice.discs.AddonConfig$Companion.loadConfig(AddonConfig.kt:142) ~[?:?] {}
72 | at su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:106) ~[?:?] {}
73 | at su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:71) ~[?:?] {}
74 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
75 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
76 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading}
77 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
78 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
79 | at net.minecraft.server.dedicated.DedicatedServer.handler$zbl000$arclight$loadPlugins(DedicatedServerMixin.java:642) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
80 | at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:158) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
81 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
82 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
83 | at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

</body>
</html>[Server thread/ERROR] [Minecraft/]: Error occurred while enabling pv-addon-discs v1.0.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.io.File org.bukkit.Bukkit.getPluginsFolder()'
	at su.plo.voice.discs.AddonConfig$Companion.getAddonFolder(AddonConfig.kt:168) ~[?:?] {}
	at su.plo.voice.discs.AddonConfig$Companion.loadConfig(AddonConfig.kt:142) ~[?:?] {}
	at su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:106) ~[?:?] {}
	at su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:71) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.5-SNAPSHOT-9931895.jar%23163!/:arclight-1.20.1-1.0.5-SNAPSHOT-9931895] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at net.minecraft.server.dedicated.DedicatedServer.handler$zbl000$arclight$loadPlugins(DedicatedServerMixin.java:642) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_[70](https://aternos.org/log/#L70)38_(DedicatedServerMixin.java:158) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_2065[80](https://aternos.org/log/#L80)_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

**Comment by Apehum** [comment]
arclight is not supported
