### ISSUE TITLE
Loading information for a YouTube track failed

### ISSUE THREAD

**Issue by ICPO** [plasmoapp/pv-addon-discs#37]
`[22:06:54 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager] Error in loading item https://www.youtube.com/watch?v=WSbPhc8ZKPM
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:240) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:252) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:248) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:101) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:66) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:44) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:216) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.5
  java.runtime.version: 17.0.5+9-LTS-191
  java.vm.version: 17.0.5+9-LTS-191
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:66) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        ... 14 more
Caused by: java.io.IOException: Invalid status code for video page response: 400
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:157) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6 (2).jar:?]
        ... 14 more`

**Comment by Apehum** [comment]
Use this version of lavaplayer-lib: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.7

**Comment by ICPO** [comment]
Thanks!
