### ISSUE TITLE
Custom records refuse to work

### ISSUE THREAD

**Issue by McRa1nY** [plasmoapp/pv-addon-discs#38]
[23:34:43 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
[23:34:43 INFO]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] Updating YouTube visitor id (current is null).
[23:34:43 INFO]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] Updating YouTube visitor id succeeded, new one is CgtUUDRRU29LbnVlcyjjj7OvBjIOCgJQTBIIEgQSAgsMIEs6CiD6s-qBtvyx9mU%3D, next update will be after 600 seconds.
[23:34:43 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager] Error in loading item LZ4k_8a1c74
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:240) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:252) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:248) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:44) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:216) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
	Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 6.1.0-10-amd64
  java.vendor: Eclipse Adoptium
  java.version: 17.0.10
  java.runtime.version: 17.0.10+7
  java.vm.version: 17.0.10+7
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:66) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	... 12 more
Caused by: java.io.IOException: Invalid status code for video page response: 400
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:157) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	... 12 more

How to fix it? This problem appeared not so long ago. Up to that point everything was working great. I do not know what to do. Please, help.

**Comment by McRa1nY** [comment]
I don’t know if anyone has already had similar problems, but I haven’t found a solution yet.

**Comment by McRa1nY** [comment]
I found a closed ticket with a new version of the lavaplayer library, updating it, everything worked.
