### ISSUE TITLE
lateinit property voiceServer has not been initialized

### ISSUE THREAD

**Issue by Valpyx** [plasmoapp/pv-addon-discs#46]
![изображение_2024-04-08_104913793](https://github.com/plasmoapp/pv-addon-discs/assets/161838401/bd22dd17-58cb-492c-b4e2-1ad30bdc4770)
![image](https://github.com/plasmoapp/pv-addon-discs/assets/161838401/336aa73e-b15e-401c-9dc1-263b5848f710)

**Comment by Apehum** [comment]
Please provide full log file

**Comment by Valpyx** [comment]
org.bukkit.command.CommandException: Cannot execute command 'pv-addon-discs:disc' in plugin pv-addon-discs v1.0.5 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-398]
at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-398]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2216) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2176) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1350) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.20.4.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.4.jar:git-Paper-398]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Apehum** [comment]
This is not log FILE, attach your .log file here

**Comment by Valpyx** [comment]
Where i can get him?
Just file where .log 
![image](https://github.com/plasmoapp/pv-addon-discs/assets/161838401/2e26ac0f-f878-4c53-afe2-caa0200d485d)
this?

**Comment by Apehum** [comment]
Logs files are located in the `logs` folder. Find the log file with the error (should be just `latest.log` in most cases) and attach it here

**Comment by Valpyx** [comment]
[latest.log](https://github.com/plasmoapp/pv-addon-discs/files/14904456/latest.log)

**Comment by Valpyx** [comment]
Do you know how to fix it?

**Comment by Apehum** [comment]
This is a bug in Plasmo Voice 2.0.x, which unfortunately can't be fixed. I'm currently working on updating the addons for 2.1.x, but pv-addon-discs is not available yet. I'm working on it, so I think prerelease will be available tomorrow

**Comment by Valpyx** [comment]
Ok, thanks!
I will be waiting for update

**Comment by Apehum** [comment]
All server-side addons are now available for 2.1.x. You can find 2.1.0-SNAPSHOT and links for the updated addons here: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT

**Comment by apehum** [comment]
https://modrinth.com/plugin/plasmo-voice/versions?c=alpha
https://modrinth.com/plugin/pv-addon-discs/versions?c=alpha
https://modrinth.com/plugin/pv-addon-lavaplayer-lib/versions?c=alpha
