### ISSUE TITLE
Plugin doesn't work on Paper 1.20.1

### ISSUE THREAD

**Issue by meshoksnega** [plasmoapp/pv-addon-discs#51]
Hi owner or Server administrators

I got problem about pv-addon-disc paper 1.20.1

plugman load pv-addon-disc
```
[18:36:47 WARN]: Unexpected exception while parsing console command "plugman load pv-addon-disc"
org.bukkit.command.CommandException: Unhandled exception executing command 'plugman' in plugin PlugManX v2.3.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.onLoad()" because "target" is null
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:438) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```
        
        
I used Plugman for reload and reloading server fully.

**Comment by meshoksnega** [comment]
New error
```
[19:15:57 WARN]: org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?
[19:15:57 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:124)
[19:15:57 WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[19:15:57 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:124)
[19:15:57 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)
[19:15:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406)
[19:15:57 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:429)
[19:15:57 WARN]:        at PlugManX.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116)
[19:15:57 WARN]:        at PlugManX.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97)
[19:15:57 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:15:57 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[19:15:57 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[19:15:57 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972)
[19:15:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
[19:15:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[19:15:57 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[19:15:57 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[19:15:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:15:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[19:15:57 INFO]: [PlugMan] That file is not a valid plugin.
```

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs/issues/82#issuecomment-2523099880
