### ISSUE TITLE
Short term of music

### ISSUE THREAD

**Issue by Aladka228** [plasmoapp/pv-addon-discs#56]
Hi,

Music plays ~30 sec and then not able to play.

Code:
[01:15:01 WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.NoSuchMethodError: 'boolean org.bukkit.block.Jukebox.startPlaying()'
[01:15:01 WARN]:        at pv-addon-discs-1.0.6.jar//su.plo.voice.discs.event.JukeboxEventListener$playTrack$1$4.invoke(JukeboxEventListener.kt:217)
[01:15:01 WARN]:        at pv-addon-discs-1.0.6.jar//su.plo.voice.discs.event.JukeboxEventListener$playTrack$1$4.invoke(JukeboxEventListener.kt:213)
[01:15:01 WARN]:        at pv-addon-discs-1.0.6.jar//su.plo.voice.discs.utils.SchedulerUtil$suspendSync$4$1.run(SchedulerUtil.kt:22)
[01:15:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[01:15:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:15:01 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[01:15:01 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[01:15:01 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[01:15:01 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[01:15:01 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[01:15:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[01:15:01 WARN]:        Suppressed: su.plo.voice.libs.kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6fae7ef0, Dispatchers.Default]

**Comment by Aladka228** [comment]
Last version of Protocolib, paper

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

If you still have any issues, please open a new issue.
