### ISSUE TITLE
Plz, update to 1.21

### ISSUE THREAD

**Issue by 44wrw44** [plasmoapp/pv-addon-discs#61]
```
[11:01:26] [Server thread/ERROR]: Error occurred while enabling pv-addon-discs v1.0.6 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS'
	at pv-addon-discs-1.0.6.jar/su.plo.voice.discs.crafting.BurnableDiscCraft.registerRecipes(BurnableDiscCraft.kt:19) ~[pv-addon-discs-1.0.6.jar:?]
	at pv-addon-discs-1.0.6.jar/su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:97) ~[pv-addon-discs-1.0.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:325) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by VadimkaG** [comment]
https://github.com/plasmoapp/pv-addon-discs/blob/main/src/main/kotlin/su/plo/voice/discs/crafting/BurnableDiscCraft.kt#L19

Replace Tag.ITEMS_MUSIC_DISCS with Tag.ITEMS_CREEPER_DROP_MUSIC_DISCS
This should work
