### ISSUE TITLE
music doesn't play

### ISSUE THREAD

**Issue by Mirise1** [plasmoapp/pv-addon-discs#68]
[13:17:01 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of eSW2LVbPThw
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 20f37dff305238a382557cb98b6b714516c23a99-SNAPSHOT
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-94-generic
  java.vendor: Eclipse Adoptium
  java.version: 21.0.3
  java.runtime.version: 21.0.3+9-LTS
  java.vm.version: 21.0.3+9-LTS
Caused by: java.lang.RuntimeException: Not success status code: 403
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        at pv-addon-lavaplayer-lib-1.0.9.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.9.jar:?]
        ... 4 more

**Comment by primtive** [comment]
same problem on youtube
soundcloud works

**Comment by Apehum** [comment]
Try with https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.10

**Comment by jackgraddon** [comment]
Just wanted to come here and say I was having the same issue, updating to lavaplayer 1.0.10 fixed it.
