### ISSUE TITLE
in the middle of the song, the song turns off and gives an error

### ISSUE THREAD

**Issue by F0NDERS** [plasmoapp/pv-addon-discs#70]
[23:00:02 WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.registryAccess()" because "this.level" is null
[23:00:02 WARN]:        at net.minecraft.world.level.block.entity.JukeboxBlockEntity.setSongItemWithoutPlaying(JukeboxBlockEntity.java:203)
[23:00:02 WARN]:        at org.bukkit.craftbukkit.block.CraftJukebox.setRecord(CraftJukebox.java:86)
[23:00:02 WARN]:        at pv-addon-discs-1.0.7.jar//su.plo.voice.discs.utils.extend.JukeboxKt.stopPlayingWithUpdate(Jukebox.kt:7)
[23:00:02 WARN]:        at pv-addon-discs-1.0.7.jar//su.plo.voice.discs.event.JukeboxEventListener$playTrack$1$5.invoke(JukeboxEventListener.kt:231)
[23:00:02 WARN]:        at pv-addon-discs-1.0.7.jar//su.plo.voice.discs.event.JukeboxEventListener$playTrack$1$5.invoke(JukeboxEventListener.kt:229)
[23:00:02 WARN]:        at pv-addon-discs-1.0.7.jar//su.plo.voice.discs.utils.SchedulerUtil$suspendSync$4$1.run(SchedulerUtil.kt:22)
[23:00:02 WARN]:        at pv-addon-discs-1.0.7.jar//su.plo.voice.discs.utils.SchedulerUtil.runTaskAt$lambda-3(SchedulerUtil.kt:50)
[23:00:02 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
[23:00:02 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[23:00:02 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1657)
[23:00:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471)
[23:00:02 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538)
[23:00:02 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[23:00:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[23:00:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[23:00:02 WARN]:        Suppressed: su.plo.voice.libs.kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@71695bae, Dispatchers.Default]

**Comment by Apehum** [comment]
This was a bug in Paper, which was fixed by https://github.com/PaperMC/Paper/commit/b4b820851f5291c467b1a9590750a10ec67af4f6
I guess Folia is just not updated yet, so the fix isn't there. I can't do anything from my side, so you'll just have to wait for Folia to update

**Comment by F0NDERS** [comment]
Thank's
