### ISSUE TITLE
The track cannot be played

### ISSUE THREAD

**Issue by MaximusPatotus** [plasmoapp/pv-addon-discs#74]
java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS'
	at CoreProtect-22.4.jar/net.coreprotect.listener.player.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:687) ~[CoreProtect-22.4.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:27:53] [DefaultDispatcher-worker-2/INFO]: [pv-addon-discs] Starting track job "Billie Eilish - CHIHIRO (Official Music Video)" with distance 64 at Location{world=CraftWorld{name=world},x=162.0,y=71.0,z=88.0,pitch=0.0,yaw=0.0}
[19:27:53] [DefaultDispatcher-worker-2/INFO]: [pv-addon-discs] Starting track "Billie Eilish - CHIHIRO (Official Music Video)" on su.plo.voice.server.audio.source.VoiceServerStaticSource@765f9c0f
[19:27:53] [DefaultDispatcher-worker-2/INFO]: [pv-addon-discs] Track "Billie Eilish - CHIHIRO (Official Music Video)" on su.plo.voice.server.audio.source.VoiceServerStaticSource@765f9c0f was ended or cancelled

**Comment by MaximusPatotus** [comment]
![изображение_2024-07-31_193144936](https://github.com/user-attachments/assets/11bb4f15-5e11-4855-95ab-1b0972ff5b26)

**Comment by foxya27** [comment]
это ошибка core protect...
