### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Vediforce** [plasmoapp/pv-addon-discs#76]
[22:43:33 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of apDtBuiIBgA
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 6.1.0-22-amd64
  java.vendor: Oracle Corporation
  java.version: 21.0.3
  java.runtime.version: 21.0.3+7-LTS-152
  java.vm.version: 21.0.3+7-LTS-152
Caused by: java.lang.RuntimeException: Not success status code: 403
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        ... 4 more
        
        
        
      это из-за блокировки?

**Comment by minagusi** [comment]
Не знаю, у меня такая же ошибка( 
![image](https://github.com/user-attachments/assets/8e257c71-b3d0-498d-bb12-29823bf9cb5d)

**Comment by Vchugaev** [comment]
+

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

And [sign in](https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#sign-in-to-confirm-youre-not-a-bot--please-sign-in-using-youtube) to youtube using oauth. If you still have any issues, please open a new issue.
