### ISSUE TITLE
missing 1.0.10 source code

### ISSUE THREAD

**Issue by andreypfau** [plasmoapp/pv-addon-discs#77]
```
[22:40:47 INFO]: [pv-addon-lavaplayer-lib] Enabling pv-addon-lavaplayer-lib v1.0.10
[22:40:47 INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.0.8
[22:40:47 ERROR]: Error occurred while enabling pv-addon-discs v1.0.8 (Is it up to date?)
2024-08-20T22:40:47.311477635Z java.lang.NoSuchMethodError: 'void su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.YoutubeAudioSourceManager.useOauth2(java.lang.String, boolean)'
2024-08-20T22:40:47.311479779Z 	at pv-addon-discs-1.0.8.jar/su.plo.voice.discs.PlasmoAudioPlayerManager.registerSources(PlasmoAudioPlayerManager.kt:160) ~[pv-addon-discs-1.0.8.jar:?]
2024-08-20T22:40:47.311481352Z 	at pv-addon-discs-1.0.8.jar/su.plo.voice.discs.PlasmoAudioPlayerManager.<init>(PlasmoAudioPlayerManager.kt:36) ~[pv-addon-discs-1.0.8.jar:?]
2024-08-20T22:40:47.311482855Z 	at pv-addon-discs-1.0.8.jar/su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:123) ~[pv-addon-discs-1.0.8.jar:?]
2024-08-20T22:40:47.311484147Z 	at pv-addon-discs-1.0.8.jar/su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:70) ~[pv-addon-discs-1.0.8.jar:?]
2024-08-20T22:40:47.311485480Z 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
2024-08-20T22:40:47.311486792Z 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-9203a7a]
```

Looks like code in main branch is outdated

**Comment by Apehum** [comment]
Update pv-addon-lavaplayer-lib to latest pre-release: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.12
