### ISSUE TITLE
Ошибка при вопроизведении пластинки

### ISSUE THREAD

**Issue by foxya27** [plasmoapp/pv-addon-discs#79]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) ~[?:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:73) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:121) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:153) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:121) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
	... 4 more

**Comment by foxya27** [comment]
[22:04:58 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of DVIaDzs1EH4
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-119-generic
  java.vendor: Ubuntu
  java.version: 21.0.4
  java.runtime.version: 21.0.4+7-Ubuntu-1ubuntu222.04
  java.vm.version: 21.0.4+7-Ubuntu-1ubuntu222.04
Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:57) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:153) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:121) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        ... 4 more
        Suppressed: su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.ClientInformation: 
  yts.version: 1.7.1
  client.identifier: ANDROID_TESTSUITE
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) ~[?:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:73) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:121) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:153) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:121) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        at pv-addon-lavaplayer-lib-1.0.12.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.12.jar:?]
        ... 4 more

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#read-timed-out
