### ISSUE TITLE
Don't loading

### ISSUE THREAD

**Issue by meshoksnega** [plasmoapp/pv-addon-discs#82]
```
[09:40:23 WARN]: org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?

[09:40:23 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:122)

[09:40:23 WARN]: at java.base/java.util.Optional.orElseThrow(Optional.java:403)

[09:40:23 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:122)

[09:40:23 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)

[09:40:23 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:419)

[09:40:23 WARN]: at PlugManX-2.4.1.jar//com.rylinaux.plugman.pluginmanager.PaperPluginManager.load(PaperPluginManager.java:411)

[09:40:23 WARN]: at PlugManX-2.4.1.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)

[09:40:23 WARN]: at PlugManX-2.4.1.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:94)

[09:40:23 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[09:40:23 WARN]: at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)

[09:40:23 WARN]: at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)

[09:40:23 WARN]: at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)

[09:40:23 WARN]: at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)

[09:40:23 WARN]: at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)

[09:40:23 WARN]: at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)

[09:40:23 WARN]: at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)

[09:40:23 WARN]: at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)

[09:40:23 WARN]: at net.minecraft.commands.Commands.performCommand(Commands.java:358)

[09:40:23 WARN]: at net.minecraft.commands.Commands.performCommand(Commands.java:345)

[09:40:23 WARN]: at net.minecraft.commands.Commands.performCommand(Commands.java:340)

[09:40:23 WARN]: at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226)

[09:40:23 WARN]: at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200)

[09:40:23 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)

[09:40:23 WARN]: at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)

[09:40:23 WARN]: at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)

[09:40:23 WARN]: at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543)

[09:40:23 WARN]: at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354)

[09:40:23 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)

[09:40:23 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by meshoksnega** [comment]
PurPur core
1.21

**Comment by apehum** [comment]
Don't see how it's related to `pv-addon-discs`. If you think that the issue with `pv-addon-discs`, please reopen the issue and provide full server logs.
