### ISSUE TITLE
[WARN] Please sign in?

### ISSUE THREAD

**Issue by lDoomerl** [plasmoapp/pv-addon-discs#83]
Some tracks can't be burned with error "Please sign in", 

![image](https://github.com/user-attachments/assets/d374fabb-b20a-4d81-a149-f143b0fe3427)

Some of them can be burned but with this warn:
```
[23:38:52 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Suspicious exception for playback of 6dhStCOPZGI
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.6
  os.arch: amd64
  os.name: Linux
  os.version: 5.10.0-26-amd64
  java.vendor: Oracle Corporation
  java.version: 21.0.3
  java.runtime.version: 21.0.3+7-LTS-152
  java.vm.version: 21.0.3+7-LTS-152
  ```
  
  PlasmoVoice version 2.0.10
  pv-addon-discs version 1.0.8
  pv-addon-lavaplayer-lib version 1.1.0

**Comment by le0nlol** [comment]
I have same issue but client doesn't send that red message, I only see warn in console

**Comment by le0nlol** [comment]
maybe try to update plugin to alpha version? this might work

(i tried but it didn't work, sadly)

**Comment by le0nlol** [comment]
Also I saw this message while server was starting

[13:37:10 WARN]: [su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.clients.Android] ANDROID is broken with no known fix. It is no longer advised to use this client.

**Comment by lDoomerl** [comment]
> maybe try to update plugin to alpha version? this might work
> 
> (i tried but it didn't work, sadly)

I tried alpha first, so definitely not

**Comment by le0nlol** [comment]
> > maybe try to update plugin to alpha version? this might work
> 
> > 
> 
> > (i tried but it didn't work, sadly)
> 
> 
> 
> I tried alpha first, so definitely not 

Btw I figured out that it only happens with YouTube links, try to use CloudSound

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#sign-in-to-confirm-youre-not-a-bot--please-sign-in-using-youtube

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

And [sign in](https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#sign-in-to-confirm-youre-not-a-bot--please-sign-in-using-youtube) to youtube using oauth. If you still have any issues, please open a new issue.
