### ISSUE TITLE
I can't hear anything

### ISSUE THREAD

**Issue by le0nlol** [plasmoapp/pv-addon-discs#84]
I burn disc with youtube video and when I put it with jukebox, I can't hear it

**Comment by le0nlol** [comment]
error log from console:


[13:08:04 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Suspicious exception for playback of _NZgtPIEEmM
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.6
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 21.0.4
  java.runtime.version: 21.0.4+8-LTS-274
  java.vm.version: 21.0.4+8-LTS-274

**Comment by le0nlol** [comment]
![image](https://github.com/user-attachments/assets/389d6f32-71a2-408e-be29-9b5e6c666216)
