### ISSUE TITLE
Не воспроизводится звук с пластинки

### ISSUE THREAD

**Issue by ladieeez** [plasmoapp/pv-addon-discs#85]
Здравствуйте! На сервере установлен  pv-addon-discs 1.1.2 и pv-addon-lavaplayer-lib 1.1.2
Ошибки никакой не выдает, на пластинку спокойно устанавливается трек, но когда вставляешь в проигрыватель - звука нет. В настройках войса звук с пластинок на максимум.
Плагин версии 2.1.1 paper, мод версии 2.1.1 fabric
Сервер находится в РФ

upd: Ошибку или что-то подобное все же выдало

```
[su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.http.YoutubeAccessTokenTracker] Updating YouTube visitor id succeeded, new one is CgtEc3I5cE9TVVlQZyjv8q-5BjIKCgJSVRIEGgAgVToMCAEgy56glfWt_pVn, next update will be after 600 seconds.
[02:19:11 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Suspicious exception for playback of iggmiF7DNoM
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.6
  os.arch: amd64
  os.name: Linux
  os.version: 6.1.0-23-amd64
  java.vendor: Oracle Corporation
  java.version: 21.0.2
  java.runtime.version: 21.0.2+13-LTS-58
  java.vm.version: 21.0.2+13-LTS-58
```

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

And [sign in](https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#sign-in-to-confirm-youre-not-a-bot--please-sign-in-using-youtube) to youtube using oauth.
