### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheRa1nY** [plasmoapp/pv-addon-discs#87]
[21:24:53 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of KBtk5FUeJbk
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.6
  os.arch: amd64
  os.name: Linux
  os.version: 6.1.0-17-amd64
  java.vendor: Oracle Corporation
  java.version: 21.0.2
  java.runtime.version: 21.0.2+13-LTS-58
  java.vm.version: 21.0.2+13-LTS-58
Caused by: java.io.IOException: Invalid status code for player api response: 400
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadJsonResponse(NonMusicClient.java:67) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:107) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:193) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:119) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        at pv-addon-lavaplayer-lib-1.1.0.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.1.0.jar:?]
        ... 4 more

**Comment by apehum** [comment]
#86
