### ISSUE TITLE
Minecraft 1.21.1 pv-addon-discs v1.1.3 (Is it up to date?)

### ISSUE THREAD

**Issue by cloverskid** [plasmoapp/pv-addon-discs#89]
Hello. 
Server version: 1.21.1 paper
pv-addon-discs version: 1.1.3 (latest)
Lavaplayer-lib version: 1.1.2 (latest)
On Modrinth pv-addon-discs version 1.1.3 is listed as supporting 1.21.1
Tried pv-addon-discs 1.1.2, it enabled but commands is not working. Something about subcommands, I will send error later.
Also both versions didn't loaded "languages" folder, I tried to load it by myself, but it still not working.
`[14:58:41 INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.1.3
[14:58:41 INFO]: [pv-addon-discs] YouTube clients: [MUSIC, ANDROID_VR, WEB, WEBEMBEDDED, TVHTML5EMBEDDED]
[14:58:41 ERROR]: Error occurred while enabling pv-addon-discs v1.1.3 (Is it up to date?)
java.lang.NoClassDefFoundError: su/plo/voice/lavaplayer/libs/dev/lavalink/youtube/clients/AndroidVr
        at pv-addon-discs-1.1.3.jar/su.plo.voice.discs.config.YoutubeClient._init_$lambda$5(YoutubeClient.kt:23) ~[pv-addon-discs-1.1.3.jar:?]
        at pv-addon-discs-1.1.3.jar/su.plo.voice.discs.PlasmoAudioPlayerManager.registerSources(PlasmoAudioPlayerManager.kt:246) ~[pv-addon-discs-1.1.3.jar:?]
        at pv-addon-discs-1.1.3.jar/su.plo.voice.discs.PlasmoAudioPlayerManager.<init>(PlasmoAudioPlayerManager.kt:55) ~[pv-addon-discs-1.1.3.jar:?]
        at pv-addon-discs-1.1.3.jar/su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:177) ~[pv-addon-discs-1.1.3.jar:?]
        at pv-addon-discs-1.1.3.jar/su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:107) ~[pv-addon-discs-1.1.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.clients.AndroidVr
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 15 more
[14:58:41 INFO]: [pv-addon-discs] Disabling pv-addon-discs v1.1.3
[14:58:41 INFO]: [PlasmoVoice] Addon pv-addon-discs v1.1.3 by KPidS, Apehum unloaded`

**Comment by apehum** [comment]
If someone will have the same issue update pv-addon-lavaplayer-lib to the latest available version.
